project:
  type: website
  output-dir: docs

website:
  title: "Pollinator contribution to crop yield\n"
  sidebar:
    background: primary
    # logo: "images/logo.png"
    pinned: true
    align: center
    tools:
      - icon: github
        href: https://github.com/ibartomeus/CropPollinationModels
        text: GitHub
      - icon: twitter
        href: https://twitter.com
    style: floating
    search: true
    contents:
      - href: index.qmd
        text: Home
      - href: introduction.qmd
        text: Introduction
      - href: results.qmd
        text: Results
      - href: methods.qmd
        text: Methods
      - href: what_next.qmd
        text: What next? 
      - href: references.qmd
        text: References  
      

format:
  html:
    theme: minty
    #css: styles.css
    toc: true
    