---
title: "Pollinator contribution to crop yield"
format: html
editor: visual
editor_options: 
  chunk_output_type: console
---

```{r load_things, echo=FALSE, message=FALSE, warning=FALSE, paged.print=FALSE}
library(gh) #How heavy would this library be?
releases <- gh("GET /repos/ibartomeus/OBservData/releases", 
   owner = "ibartomeus",
   repo = "OBservData")
versionCropPol <- releases[[1]][["tag_name"]]

#readLines("https://github.com/ibartomeus/OBservData/releases/latest") #can we do this using base r? This web resolves to the last tag...

releases <- gh("GET /repos/ibartomeus/CropPollinationModels/releases", 
   owner = "ibartomeus",
   repo = "CropPollinationModels")
versionCropPollinationModels <- releases[[1]][["tag_name"]]

estimates <- read.csv("scripts/estimates_data.csv")
```

## Authors

James Reilly^1^, Alfonso Allen-Perkins^2^, Rachael Winfree^1^, Ignasi Bartomeus^2^

> (1) Department of Ecology, Evolution and Natural Resources, Rutgers University, New Brunswick, NJ, USA
>
> (2) Estación Biológica de Doñana (EBD-CSIC), Avenida Américo Vespucio 26, E-41092 Sevilla, Spain. Corresponding email: [nacho.bartomeus\@gmail.com](mailto:nacho.bartomeus@gmail.com)

**Last update:** `r Sys.Date()`

## Abstract

Over 75% percent of the world's food crops are dependent on pollinators to at least some degree (IPBES 2017). However, the precise degree of pollinators contribution to crop yield is uncertain because there is a large variability in crop types, pollinator communities, agricultural practices and environmental contexts. Fortunately, since the first case studies reporting a positive effect of pollinators on crop yield, more and more data has accumulated. This allowed us to synthesize what we know (e.g. Garibaldi et al 2013, Rader et al. 2016, Dainese et al 2019). However, as the question is data hungry and is still not settled, we aim to embrace this uncertainty and periodically report updates as our knowledge increases. This repository uses CropPol `r versionCropPol`, an open database with `r estimates[nrow(estimates), "n"]` studies to regress the abundance and richness of wildbees and honeybees on crop yield. Currently, the overall estimate of wild bee abundances is `r round(estimates[nrow(estimates), "estimate_WI"], 3)` and that of honeybees is `r round(estimates[nrow(estimates), "estimate_HB"], 3)`. Pollinator richness has an estimate of `r `round(estimates[nrow(estimates), "estimate_richness"], 3).` By providing a dynamic assessment of how our knowledge changes as more data is available, we ensure updated answers to key questions in ecology.

### How to cite this:

You can cite this dynamic document directly: J. Reilly, A. Allen-Perkins, R. Winfree, I. Bartomeus. `r substr(Sys.Date(), 1, 4)` Pollinator contribution to crop yield. version `r versionCropPollinationModels`. DOI: [10.5281/zenodo.7481551](https://doi.org/10.5281/zenodo.7481551).

Or the original paper: TBA

### Download in PDF:

<https://ibartomeus.github.io/CropPollinationModels/Report_CropPolModels.pdf>

### Source code:

You can find the source code, as well as previous releases of this repository at: <https://github.com/ibartomeus/CropPollinationModels>
