---
title: "Pollinator contribution to crop yield"
format: html
editor: visual
---

::: {.content-visible when-format="html"}
# Introduction
:::

Over 75% percent of the world's food crops are dependent on pollinators to at least some degree (IPBES 2017). In most crop systems, pollination is provided through a combination of managed honey bees and wild insects, which consist primarily of wild bees, but also flies and other insects (Larson et al. 2001, Rader et al. 2016). Despite not being managed for crop pollination, wild insects often make up a significant fraction of total flower visits and can even be the dominant pollinators in situations where agricultural intensity and/or land use is not extreme (Kremen et al. 2002, Ricketts et al. 2008, Garibaldi et al. 2011, Kennedy et al. 2013, Koh et al. 2016, Reilly et al. 2020).

There is emerging evidence that wild insect visits may increase crop yields per capita more strongly than honey bees (Winfree et al. 2007, Garibaldi et al. 2013, Mallinger and Gratton 2015, Blitzer et al. 2016), and that honey bees alone can be insufficient for eliminating pollination limitation for many crops (Sáez et al. 2022). The mechanism for this is not well understood but could be due to wild bees depositing higher amounts of pollen per visit (Winfree et al. 2007, Park et al. 2016, Eeraerts et al. 2019), or to differences in the behavior of wild bees and the honey bee (Greenleaf and Kremen 2006, Brittain et al. 2013).

Given the potential for different pollinator groups to have different impacts on crop yields, there is a broader debate about whether it is simply the number of individual pollinator visits that matters for yield, or whether pollinator biodiversity (generally measured as the number of pollinator species) is also important. In fact, this question is part of a major debate in ecology about whether the maintenance of ecosystem services (or functions) requires a diverse community of species, or whether most services result from the additive contributions of a few dominant species (Cardinale 2012, Bommarco et al. 2013). Within the pollination literature, pollinator species richness (i.e., the number of pollinator species present) has been shown to be positively associated with crop productivity (Garibaldi et al. 2015, Garibaldi et al. 2016, Dainese et al. 2019), particularly when pollination needs to be provided across many sites or years (e.g., Klein et al. 2003, Winfree et al. 2018, Lemanski et al 2022, other citations). At the same time, a small number of dominant pollinator species do often provide most of the pollination for any particular crop, although the same species may not be dominant across crops, or even within a crop when space and time are considered (Winfree et al. 2015, Kleijn et al. 2015, Genung et al. 2020, Winfree et al 2018 Science, Genung et al 2022).

Here we use a recently published, global compilation of data on crop yield and flower visitation by wild and managed pollinators that roughly doubles the data available for previous analyses (Allen-Perkins et al. 2022) to answer the following three questions:

1\) What are the relative contributions of honey bees versus wild insects to crop visitation worldwide?

2\) What are the relative contributions of honey bees versus wild insects to crop yield worldwide?

3\) Is the total number of flower visits by pollinators sufficient to predict crop yields, or is the diversity of pollinator species also important?

4\) How the relationships between pollinator visits, richness, and yield has changed as the number of studies available grows?
