---
title: "Pollinator contribution to crop yield"
format: html
editor: visual
---

::: {.content-visible when-format="html"}
# Methods
:::

## The CropPol database

Our analysis uses the CropPol database (Allen-Perkins et al. 2022) as is basis. CropPol is an open and dynamic (i.e., periodically updated) database of crop pollination studies. The majority of these datasets provided data on both insect visitation rates and crop yields or related measurements and were used in the analyses conducted for this paper. Within each study, the most basic unit of observation at which pollinator visit counts and the resulting yield can be paired was the site-year ("site" is typically a field or part of a field). Some sites were sampled for multiple years, but single-year sites were also common. In our analyses, we allowed multiple years of data to be part of the same study as long as the collection methods did not change. We only included studies with at least three site-years. As expected, studies from Europe and North America were somewhat overrepresented in our sample. It is also likely that even within regions there are biases in the landscapes where studies were located and in which crops were selected. This limits our ability to infer patterns on a global scale, but currently represents the best available data.

A strength of the dynamic database is that it will allow continuous updates to our analysis as the number of available studies grows.

## Data processing

Across the all datasets, the number of pollinators visiting flowers was measured in two different ways: either by observing the number of insects visiting flowers per unit time (a true visit rate), or by netting insects visiting flowers and summing the number of specimens collected. In the context of crop pollination studies, the latter data type is commonly referred to as "net data", and might be more accurately described as visitor abundance on flowers than as a true visit rate. In this analysis, we used the two interchangeably as "number of visits". If both types of measurements were available for a given dataset, preference was given to true visit rates; any potential variation in mean or variance that might result from the different collection methods across studies should be mitigated because we converted all values to z-scores for the analysis. We chose to combine the visits by all pollinators other than the honey bee into a "wild insects" group. Thus we compared two main groups, honey bee (HB) and wild insects (WI), consistent with previous analyses (e.g. Garibaldi et al. 2013). We did not drop studies that found or reported only bees as visitors, on the assumption that researchers for the most part did not neglect sampling insect groups that were important for the pollination of their crop. We did however drop studies that specifically focused on wild insect visitation and did not record honey bee visits at all, because these studies would misattribute to wild insects the yield due to honey bees. We did not need to do a similar filtering step for wild insects because wild insects were recorded in all studies.

Crop yield is defined as the amount of agricultural production harvested per unit of harvested area. In our datasets, often this was simply kg per unit area, but sometimes was more specific to the crop, e.g., kg per plant, fruit per branch, fruit/seed set, etc. When more than one production variable was provided, we used the variable listed by the data providers as "yield" in the online database as opposed to the alternative "yield2." We did not include any studies that only estimated pollen deposition (visits multiplied by pollen per visit) because this not a direct measurement of the effect of pollinator visitation. As above for insect visitation rates, we performed analyses on z-scores to mitigate differences in scale between metrics.

## Statistical analysis

To determine whether crop yields increased in the presence of more wild insect species or whether it was simply the total number of insect visits to flowers that was important, we analyzed a new set of models that contained pollinator species richness in addition to flower visitation rate by honey bees and wild insects... \[I will probably show only a single model including both richness and abundance\].

We analyzed the full model that contained pollinator species richness in addition to flower visitation rate by honey bees and wild insects, as well as the interaction between wild insects and honeybees, wild insects and richness and honeybees and richness (Model R18 in Reilly et al 2023). All models included both random intercepts and slopes for the predictor variable study. We chose to fit random slopes in addition to random intercepts because it is reasonable to assume that the slope of the relationship between visits and yield could vary across crop studies for any number of reasons that might differ across crops such as degree of pollinator dependence (Klein et al. 2007), bloom phenology, or management practices. In all models, visits by each insect group and the outcome variable (yield) were transformed to z-scores prior to running to model, so the slopes of the fixed effect estimates from the model were interpreted as effect sizes for comparison. Details on alternative models can be found in Reilly et al 2023.
