---
title: "Pollinator contribution to crop yield"
format: html
editor: visual
---

::: {.content-visible when-format="html"}
# References
:::

\- Allen-Perkins A, et al. 2022 CropPol: a dynamic, open and global database on crop pollination. Ecology 103 (3): e3614.

\- Blitzer E, et al. 2016 Pollination services for apple are dependent on diverse wild bee communities. Agric. Ecosyst. Environ. 221, 1-7. 

\- Bommarco R, et al. 2013 Ecological intensification: harnessing ecosystem services for food security. TREE 28 (4): 230-238.

\- Brittain C, et al. 2013 Synergistic effects of non-Apis bees and honey bees for pollination services. Proc. R. Soc. B 280: 1754.

\- Cardinale B, et al. 2012 Biodiversity loss and its impact on humanity. Nature 486, 59–67.

\- Dainese M, et al. 2019 A global synthesis reveals biodiversity-mediated benefits for crop production. Science Advances 5: eaax0221.

\- Eeraerts M, et al. 2019 Pollination efficiency and foraging behavior of honey bees and non-Apis bees to sweet cherry. Agric. For. Entomol. 22, 75–82. 

\- Garibaldi L, et al. 2011 Global growth and stability of agricultural yield decrease with pollinator dependence. PNAS 108, 5909–5914. 

\- Garibaldi L, et al. 2013 Wild pollinators enhance fruit set of crops regardless of honey-bee abundance. Science 339, 1608–1611. 

\- Garibaldi, et al. 2015 Trait matching of flower visitors and crops predicts fruit set better than trait diversity. JAE 52: 1436-1444.

\- Garibaldi, et al. 2016 Mutually beneficial pollinator diversity and crop yield outcomes in small and large farms. Science 351: 388-391.

\- Genung M, et al. 2020 Species loss drives ecosystem function in experiments, but in nature the importance of species loss depends on dominance. Global Ecology and Biogeography 29: 1531-1541.

\- Genung M, et al. 2022 Rare and declining bee species are key to consistent pollination of wildflower and crops across large spatial scales. Ecology 104: e3899.

\- Greenleaf S, Kremen C. 2006 Wild bees enhance honey bees pollination of hybrid sunﬂower. PNAS
USA 103, 13 890–13 895. 

\- IPBES. 2017 The assessment report of the Intergovernmental Science-Policy Platform on Biodiversity and Ecosystem Services on pollinators, pollination and food production (eds S Potts, et al.). Bonn, Germany: IPBES.

\- Kennedy C, et al. 2013 A global quantitative synthesis of local and landscape effects on wild bee
pollinators in agroecosystems. Ecol. Lett. 16, 584–599. 

\- Kleijn D, et al. 2015 Delivery of crop pollination services is an insufficient argument for wild
pollinator conservation. Nat. Commun. 6, 1–24. 

\- Klein A, et al. 2003 Fruit set of highland coffee increases with the diversity of pollinating bees, Proc. R. Soc. Lond. B 270: 955-961.

\- Klein A, et al. 2007 Importance of pollinators in changing landscapes for world crops. Proc. Biol. Sci. 274, 303–313.

\- Koh I, et al. 2016 Modeling the status, trends, and impacts of wild bee abundance in the United States. PNAS 113, 140–145. 

\- Kremen C, et al. 2002 Crop pollination from native bees at risk from agricultural intensification. PNAS 99, 16 812–16 816.

\- Larson B, et al 2001 Flies and flowers: Taxonomic diversity of anthophiles and pollinators. Can Entomol 133(4): 439–465.

\- Lemanski N, et al. 2022 Greater bee diversity is needed to maintain crop pollination over time. Nature Ecology and Evolution 6: 1516-1523.

\- Mallinger R, Gratton C. 2015 Species richness of wild bees, but not the use of managed honeybees, increases fruit set of a pollinator-dependent crop. J Appl Ecol 52: 323-330.

\- Park M, et al. 2016 Per-visit pollinator performance and regional importance of wild Bombus and Andrena (Melandrena) compared to the managed honey bee in New York apple orchards. Apidologie 47: 145-160.

\- Rader R et al. 2016 Non-bee insects are important contributors to global crop pollination. PNAS 113, 146–151. 

\- Reilly J et al. 2020 Crop production in the USA is frequently limited by a lack of pollinators. Proceedings of the Royal Society B 287: 20200922.

\- Reilly J, et al. 2023 Wild insects and honey bees are equally important to crop yields in a global analysis. Submitted manuscript.

\- Ricketts T, et al. 2008 Landscape effects on crop pollination services: are there general patterns? Ecol.
Lett. 11, 499–515. 

\- Saez A, et al. 2022 Managed honeybees decrease pollination limitation in self-compatible but not in self-incompatible crops. Proceedings of the Royal Society B 289: 20220086.

\- Winfree R, et al. 2007 Native bees provide insurance against ongoing honey bee losses. Ecol. Lett. 10, 1105–1113. 

\- Winfree R, et al. 2015 Abundance of common species, not species richness, drives delivery of a real-world ecosystem service. Ecology Letters 18: 626-635.  

\- Winfree R, et al. 2018 Species turnover promotes the importance of bee diversity for crop pollination at regional scales. Science 359: 791-793.

