---
title: "Results"
format: html
editor: visual
editor_options: 
  chunk_output_type: console
---

```{r load_things, echo=FALSE, message=FALSE, warning=FALSE, paged.print=FALSE}
# source the script to read and clean data
source("scripts/read_data.R")
library(lme4)

```

## How are the main crop visitors?

```{r Fig1, echo=FALSE, message=FALSE, warning=FALSE, paged.print=FALSE}
# run the main models-----
# analysis: proportion of visits by HB vs WI, or HB, wild bees, and non bees

# fraction of visits by WI boxplot

# calculate fraction of "visits" by each group
field_data8a$fracWI = field_data8a$wild_insects/field_data8a$all_insects
field_data8a$fracHB = field_data8a$honeybee/field_data8a$all_insects

# reorder factor levels of study so they will plot in order of increasing median when we run a boxplot
field_data8a$study_id2 <- reorder(field_data8a$study_id2, field_data8a$fracWI, median, na.rm=T)

#png(filename = "wild insect visits by crop boxplots 11-16-2022.png", width = 9, height = 5, units = "in", bg = "white", res = 600)
par(mar=c(4,4,4,4))
boxplot(data=field_data8a, fracWI ~ study_id2, col=c("light gray"), xaxt = 'n', xlab="study", ylab="proportion of visits by wild insects", las = 1)
axis(1,seq(5,90,5))
#dev.off()



```

## Which effect has honeybee and wild pollinator visits on yield?

```{r Fig2, echo=FALSE, message=FALSE, warning=FALSE, paged.print=FALSE}
# analysis: mixed models for HB vs WI------

# for this we are using field_data8a, which has HB and WI, and where we have entered manual 0's for HB z-scores in 2 systems where they were =0.
# note that some of these studies are bees only, and many do not have richness data

# note: the following models will return a warning of "boundary (singular) fit: see ?isSingular".  I think this is due to using z-scores, which make the mean of all studies =0, so it should not be a problem for the models.

mod9 = lmer(data=field_data8a, yield_z ~ wild_insects_z*honeybee_z + (1 + wild_insects_z|study_id2) + (1 + honeybee_z|study_id2) + (1 + wild_insects_z*honeybee_z|study_id2), na.action=na.fail, REML=T)

summary(mod9)

# analysis: mixed models for HB vs WI vs Richness------

# for this we are using field_data9a, which is the subset of studies providing data for HB, WI, and Richness

# I didn't get any convergence warnings when I ran these with the current data, but if it does happen, try adding one of these to the lmer statement:
# control = lmerControl(optimizer="Nelder_Mead")
# control = lmerControl(optimizer ='optimx', optCtrl=list(method='L-BFGS-B'))

# note that I'm using 0+ in the random effect instead of 1+ since all studies are z-scored and thus constrained to have a mean of 0. My logic here is that there is no need to try to estimate separate intercepts for each study. We are still estimating the random slopes as usual.

modR_18 = lmer(data=field_data9a, yield_z ~ wild_insects_z*honeybee_z + wild_insects_z*richness_z + honeybee_z*richness_z + (0 + wild_insects_z*honeybee_z|study_id2) + (0 + wild_insects_z*richness_z|study_id2) +  (0 + honeybee_z*richness_z|study_id2), na.action=na.fail, REML=T)

summary(modR_18)

# plots: random effect estimates by study, similar to Garibaldi et al 2013 fig 2b, but using model 9 -----

a=fixef(mod9)
a_wi = a[2]		#overall slope of wild insects 
a_hb = a[3]		#overall slope of honey bee 
b=ranef(mod9)
qq <- attr(ranef(mod9, condVar = TRUE)[[1]], "postVar") # Extract the variances of the random effects
qq_wi = qq[[1]]
qq_hb = qq[[2]]
e_wi=(sqrt(qq_wi))	
e_wi=e_wi[2,2,]		
e_hb=(sqrt(qq_hb))	
e_hb=e_hb[2,2,]		
b_wi = b[[1]][2]	# slope of wild insects by crop?  lmer calls this the conditional mean
b_hb = b[[1]][4]	# slope of hb by crop?  lmer calls this the conditional mean
mean_wi=(b_wi+a_wi)			# mean ...  add by crop part to overall slope
ci_lower_wi=(b_wi+a_wi)-(e_wi*2)	# lower CI
ci_upper_wi=(b_wi+a_wi)+(e_wi*2)	# upper CI
mean_hb=(b_hb+a_hb)			# mean ...  add by crop part to overall slope
ci_lower_hb=(b_hb+a_hb)-(e_hb*2)	# lower CI
ci_upper_hb=(b_hb+a_hb)+(e_hb*2)	# upper CI

###
modelout = cbind(mean_wi, ci_lower_wi, ci_upper_wi, mean_hb, ci_lower_hb, ci_upper_hb)
colnames(modelout)[1] = "mean_wi"
colnames(modelout)[2] = "ci_lower_wi"
colnames(modelout)[3] = "ci_upper_wi"
colnames(modelout)[4] = "mean_hb"
colnames(modelout)[5] = "ci_lower_hb"
colnames(modelout)[6] = "ci_upper_hb"

modelout$crop = rownames(modelout)
#modelout

modelout_mod9 = modelout

# plot figure 2
#png(filename = "slopes by crop MODEL 5 10-25-2022.png", width = 10, height = 5, units = "in", bg = "white", res = 600)

par(mfrow=c(1,2))

modelout_mod9 = modelout_mod9[order(mean_wi), , drop = FALSE]
plot(1:nrow(modelout_mod9), modelout_mod9$mean_wi, pch=19, col="#00bb5c", ylim=c(-.75,.75), ylab="wild insect slope (mean and 95% CI)", cex=1.5, xaxt = "n", xlab="crop study", main="Wild Insects")
axis(1, at=seq(0,nrow(modelout_mod9),10), labels=seq(0,nrow(modelout_mod9),10))
arrows(1:nrow(modelout_mod9), modelout_mod9$ci_lower_wi, 1:nrow(modelout_mod9), modelout_mod9$ci_upper_wi, length=0.05, angle=90, code=3, col="#00bb5c", lwd=1.5)
abline(h=0.060, lty="dashed", lwd=2)
abline(h=0, lwd=1, col="black", lty="dotted")

modelout_mod9 = modelout_mod9[order(mean_hb), , drop = FALSE]
plot(1:nrow(modelout_mod9), modelout_mod9$mean_hb, pch=19, col="#c96d00", ylim=c(-.75,.75), ylab="honey bee slope (mean and 95% CI)", cex=1.5, xaxt = "n", xlab="crop study", main="Honey Bee")
axis(1, at=seq(0,nrow(modelout_mod9),10), labels=seq(0,nrow(modelout_mod9),10))
arrows(1:nrow(modelout_mod9), modelout_mod9$ci_lower_hb, 1:nrow(modelout_mod9), modelout_mod9$ci_upper_hb, length=0.05, angle=90, code=3, col="#c96d00", lwd=1.5)
abline(h=0.070, lty="dashed", lwd=2)
abline(h=0, lwd=1, col="black", lty="dotted")

#dev.off()


```

## How estimates changed over time?

```{r Fig3, echo=FALSE, message=FALSE, warning=FALSE, paged.print=FALSE}

estimates <- read.csv("scripts/estimates_data.csv")
plot(estimates$estimate_HB, t = "b", col = "red", las = 1, xlab = "", ylab = "estimates", ylim = c(-0.5, 0.5),  xaxt = "n")
axis(1, at = 1:nrow(estimates), labels = estimates$timepoint, las=2, cex.axis = 0.7)
points(estimates$estimate_WB, t = "b", col = "green")
```
